### ISSUE TITLE
Please Make Puplic

### ISSUE THREAD

**Issue by SubjectQuit** [Tommy131/KraftAufFlaeche#10]
Hey can you make this Repo public?

**Comment by Tommy131** [comment]
All right, I changed the visibility.

________________________________
发件人: SubjectQuit ***@***.***>
发送时间: 2024年10月10日 5:43 下午
收件人: Tommy131/KraftAufFlaeche ***@***.***>
抄送: HanskiJay ***@***.***>; Assign ***@***.***>
主题: [Tommy131/KraftAufFlaeche] Please Make Puplic (Issue #10)


Hey can you make this Repo public?

―

**Comment by SubjectQuit** [comment]
Thank you
